web/router.ex
defmodule Codemash2016.Router do
  use Codemash2016.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Codemash2016 do
    pipe_through :browser # Use the default browser stack

    get "/", GameController, :index

    get "/start", GameController, :start
    get "/game/:game_code", GameController, :game
    get "/join/:game_code", GameController, :join
  end

  # Other scopes may use custom stacks.
  # scope "/api", Codemash2016 do
  #   pipe_through :api
  # end
end

lib/codemash2016/endpoint.ex
defmodule Codemash2016.Endpoint do
  use Phoenix.Endpoint, otp_app: :codemash2016

  socket "/socket", Codemash2016.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :codemash2016, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_codemash2016_key",
    signing_salt: "FRer/ucr"

  plug Codemash2016.Router
end

lib/codemash2016/game.ex
defmodule Codemash2016.Game do
  alias Codemash2016.Game
  use Timex

  @players     %{"player_one" => :player_one_move, "player_two" => :player_two_move}

  defstruct game_code: nil, player_one_name: nil, player_one_move: nil,
  player_two_name: nil, player_two_move: nil, started: false, outcome: nil,
  rematch: nil

  def generate_game_code do
    :crypto.hash(:sha256, Integer.to_string(Time.now(:usecs)))
    |> Base.encode16
    |> String.slice(0, 5)
    |> String.upcase
  end

  @doc"""
  Returns true if the `game` is missing either player, false otherwise.
  """
  # def waiting_for_players?(game) do
  #   is_nil(player_one_name(game)) or is_nil(player_two_name(game))
  # end

  def waiting_for_players?(%Game{player_one_name: p1}) when is_nil(p1), do: true
  def waiting_for_players?(%Game{player_two_name: p2}) when is_nil(p2), do: true
  def waiting_for_players?(_game), do: false

  @doc"""
  Returns true if both players have joined. Inverse of `waiting_for_players?`
  """
  def all_players_joined?(game), do: !waiting_for_players?(game)

  @doc"""
  Returns player one's name, or nil if player one hasn't joined.
  """
  def player_one_name(game), do: game.player_one_name

  @doc"""
  Returns player two's name, or nil if player two hasn't joined.
  """
  def player_two_name(game), do: game.player_two_name

  @doc"""
  Adds a player named `name` into the player one slot on `game`
  """
  def add_player(game, "player_one", name) do
    %{game | player_one_name: name}
  end

  @doc"""
  Adds a player named `name` into the player two slot on `game`
  """
  def add_player(game, "player_two", name) do
    %{game | player_two_name: name}
  end

  @doc"""
  Makes `choice` for `player` in `game`.
  """
  def shoot(game, player, choice) do
    Map.put(game, move_string_to_atom(player), choice)
  end

  defp move_string_to_atom(string) do
    @players[string]
  end

  def set_started_flag(game = %Game{started: started}) when started, do: game
  def set_started_flag(game) do
    if all_players_joined?(game) do
      %{game | started: true}
    else
      game
    end
  end

  # SETTING OUTCOME

  ## NOOPS
  def set_outcome(game = %Game{player_one_move: p1_move}) when is_nil(p1_move), do: game
  def set_outcome(game = %Game{player_two_move: p2_move}) when is_nil(p2_move), do: game

  ## DRAWS
  def set_outcome(game = %Game{player_one_move: p1, player_two_move: p2}) when p1 == p2 do
    %{game | outcome: "draw"}
  end

  ## P1 WINS
  def set_outcome(game = %Game{player_one_move: "rock", player_two_move: "scissors"}) do
    %{game | outcome: "player_one"}
  end

  def set_outcome(game = %Game{player_one_move: "scissors", player_two_move: "paper"}) do
    %{game | outcome: "player_one"}
  end

  def set_outcome(game = %Game{player_one_move: "paper", player_two_move: "rock"}) do
    %{game | outcome: "player_one"}
  end

  ## P2 WINS
  def set_outcome(game) do
    %{game | outcome: "player_two"}
  end

  # REMATCH

  @doc """
  Set the rematch flag for `game`, indicating `player` has asked for a rematch.
  """
  def rematch(game = %Game{rematch: rematch}, player) when is_nil(rematch) do
    %{game | rematch: player}
  end

  @doc """
  Return a started game with the same players/code as `game`.
  """
  def rematch(game, _) do
    %Game{game_code: game.game_code,
          player_one_name: game.player_one_name,
          player_two_name: game.player_two_name,
          started: game.started}
  end
end

lib/codemash2016/game_bucket.ex
defmodule Codemash2016.GameBucket do
  @name __MODULE__

  ### CLIENT!

  @doc """
  Get the game for `code`. Will initialize a new game if one doesn't exist.
  """
  def game_for(code, bucket \\ @name) do
    game = get(bucket, code)
    if !game do
      game = %Codemash2016.Game{game_code: code}
      put(bucket, code, game)
    end

    game
  end

  @doc """
  Update the `game` for `code`.
  """
  def update(code, game, bucket \\ @name) do
    put(bucket, code, game)
    game
  end

  ### AGENT!

  @doc """
  Starts a new bucket of games.
  """
  def start_link(opts \\ []) do
    opts = Keyword.put_new(opts, :name, @name)
    Agent.start_link fn -> HashDict.new end, opts
  end

  @doc """
  Get a game from `bucket` by `code`
  """
  def get(bucket, code) do
    Agent.get(bucket, &HashDict.get(&1, code))
  end

  @doc """
  Put a `game` into `bucket` under `code`
  """
  def put(bucket, code, game) do
    Agent.update(bucket, &HashDict.put(&1, code, game))
  end
end

lib/codemash2016/lobby.ex
defmodule Codemash2016.Lobby do
  use GenServer

  ### DAT PUBLIC API

  @doc """
  Start the lobby server.
  """
  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, :ok, opts)
  end

  def init(:ok) do
    {:ok, HashDict.new}
  end

  ### SERVER CALLBACKS

  def handle_call({ :lookup, name }, _from, names) do
    {:reply, HashDict.fetch(names, name), names}
  end

  def handle_cast({:create, name}, name, names) do
    if HashDict.has_key(names, name) do
      {:noreply, names}
    else
      # TODO: Use a key/value server somehow, get a map of "I have this
      # connection, and I have this name. Reject duplicates?"
    end
  end
end

lib/codemash2016/repo.ex
defmodule Codemash2016.Repo do
  use Ecto.Repo, otp_app: :codemash2016
end

web/controllers/game_controller.ex
defmodule Codemash2016.GameController do
  use Codemash2016.Web, :controller
  import Codemash2016.Game

  def index(conn, %{"game_code" => game_code}) do
    redirect conn, to: "/join/#{game_code}"
  end

  def index(conn, _params) do
    render conn, "index.html"
  end

  def start(conn, _params) do
    game_code = generate_game_code
    redirect conn, to: "/game/#{game_code}"
  end

  def game(conn, params) do
    render conn, "start.html", game_code: params["game_code"]
  end

  def join(conn, params) do
    render conn, "join.html", game_code: params["game_code"]
  end
end

web/views/error_view.ex
defmodule Codemash2016.ErrorView do
  use Codemash2016.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/game_view.ex
defmodule Codemash2016.GameView do
  use Codemash2016.Web, :view

end

web/views/layout_view.ex
defmodule Codemash2016.LayoutView do
  use Codemash2016.Web, :view

  @doc """
  Get the current controller name as a String. Ex: Game for GameController.
  """
  def current_controller(conn) do
    [_ | name] = Regex.run(~r/Elixir.Codemash2016.(.+)Controller/,
                           Atom.to_string(
                             Phoenix.Controller.controller_module(conn)))

    name
  end
end

web/templates/game/_moves.html.eex
<div class="moves" style="display: none;">
    <input type="button" name="rock" value="Rock" class="move input-lg col-xs-5 form-control btn-block">
    <br>
    <input type="button" name="paper" value="Paper" class="move input-lg col-xs-5 form-control btn-block">
    <br>
    <input type="button" name="scissors" value="Scissors" class="move input-lg col-xs-5 form-control btn-block">
</div>

web/templates/game/_players.html.eex
<div class="row">
    <div class="col-md-12" style="display: none;" id="outcome">
    </div>
</div>

<div class="row">
    <div class="col-md-12" style="display: none;" id="rematch_panel",>
        <input type="button" name="rematch" id="rematch" value="Rematch?" class="btn btn-info btn-lg btn-block">
    </div>
</div>

<div class="row">
    <div class="col-md-5" id="player_one">
        <div id="player_one_name_here" class="player_name"></div>
        <div id="player_one_move_here" class="player_move"></div>
        <%= render "_moves.html" %>
    </div>

    <div class="col-md-2">
        <h1 id="vs" style="display: none;">VS</h1>
    </div>

    <div class="col-md-5" id="player_two">
        <div id="player_two_name_here" class="player_name"></div>
        <div id="player_two_move_here" class="player_move"></div>
        <%= render "_moves.html" %>
    </div>
</div>

web/templates/game/index.html.eex
<div class="row">
  <div class="col-lg-6 col-md-offset-3">
      <form style="margin: 0;">
        <input type="text" name="game_code" class="input-lg col-xs-6 form-control" placeholder="Game Code" style="margin-bottom: 1em;"/>
        <input type="submit" name="join_game" id="join_game" value="Join Game" class="btn btn-success btn-lg btn-block">
      </form>

      <h2 class="center full smcap">--- or ---</h2>

      <a href="/start" class="btn btn-primary btn-lg btn-block">Start A New Game</a>
  </div>
</div>

web/templates/game/join.html.eex
<%= render "_players.html" %>

<div class="col-md-12" id="join_panel">
    <h1>Join Game <%= @game_code %></h1>
    <form>
        <label for="player_two_name">Your name:</label>
        <input type="text" name="player_two_name" id="player_two_name" class="input-lg col-xs-6 form-control">
        <input type="button" name="join_game" id="join_game" value="Join Game" class="btn btn-success btn-lg btn-block">
    </form>
</div>

<script type="text/javascript">
    window.game = require("web/static/js/game").Game;
    window.game.init('<%= @game_code %>', "player_two");
    window.game.connect();


    $("#join_game").on('click', function(e) {
      e.preventDefault();
      window.game.join("player_two", $('#player_two_name').val());
    });

    $("#player_one_name").keypress(function(e) {
        if (e.which == 13) {
            e.preventDefault();
            $('#join_game').click();
        }
    })
</script>

web/templates/game/start.html.eex
<%= render "_players.html" %>

<div class="col-md-12" id="join_panel">
    <input type="hidden" id="game_code" value="<%= @game_code %>"/>
    <div class="pregame">
        <h1>Starting Game</h1>
        <h2>Give your oppoent this link: </h2>
        <h2><%= game_url(@conn, :join, @game_code) %></h2>

        <form>
            <label for="player_one_name">Your name:</label>
            <input type="text" name="player_one_name" id="player_one_name" class="input-lg col-xs-6 form-control">
            <input type="button" name="join_game" id="join_game" value="Join Game" class="btn btn-success btn-lg btn-block">
        </form>
    </div>
</div>

<script type="text/javascript">
    window.game = require("web/static/js/game").Game;
    window.game.init($('#game_code').val(), "player_one");
    window.game.connect();

    $("#join_game").on('click', function(e) {
      e.preventDefault();
      window.game.join("player_one", $('#player_one_name').val());
    });

    $("#player_one_name").keypress(function(e) {
        if (e.which == 13) {
            e.preventDefault();
            $('#join_game').click();
        }
    })
</script>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CodeMash v.2.0.1.6</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body>
    <div class="container" role="main">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <div class="jumbotron">
          <h2>CodeMash v.2.0.1.6!</h2>
          <p class="lead">ROCK. PAPER. SCISSORS.</p>
      </div>

      <div class="row">
        <%= render @view_module, @view_template, assigns %>
      </div>

    </div> <!-- /container -->
  </body>